stages:
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-prometheus
      version: 9.1.0
      answers:
        alertmanager.enabled: "true"
      name: prometheus
      targetNamespace: prometheus
  - applyYamlConfig:
      path: ./alertmanager.yaml
timeout: 60
notification:
  recipients:
  - recipient: '@acb'
    notifier: c-fqfdk:n-4789b
  condition:
  - Success
  - Changed
  - Failed
