stages:
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-prometheus
      version: 9.1.0
      valuesYaml:
        alertmanager:
          enabled: "true"
        alertmanagerFiles:
          'alertmanager.yml':
            route:
              routes:
              - receiver: demo-alert
      name: prometheus
      targetNamespace: prometheus
timeout: 60
notification:
  recipients:
  - recipient: '@acb'
    notifier: c-fqfdk:n-4789b
  condition:
  - Success
  - Changed
  - Failed
